source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!

pod 'AFNetworking'
pod 'Mantle', '~> 2.0.6'
pod 'BlocksKit', '~> 2.2'
pod 'MBProgressHUD', '~> 0.9'

target "Test-NeonTests" do
    pod 'Expecta', '~> 1.0.0'
    pod 'OHHTTPStubs', '~> 4.0'
    pod 'OCMock', '~> 3.1'
end

